### ISSUE TITLE
TRD Error: ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by kapiltez** [tezos-reward-distributor-organization/tezos-reward-distributor#291] opened 2020-11-02 11:17 UTC
Hello Guys, I am facing issues while running trd main.py file. Mentioning my conf file, command and exact error. Thanks in advance.

Command I am running:
`python3 src/main.py -M 1 -N ALPHANET -P rpc -A https://carthagenet.smartpy.io:443 -C 400 -V`

Configuration file:
```
{
    baking_address: tz1QgArbnGonQgZXqY3bLFwC93BUCicodfPX, 
    delegator_pays_ra_fee: true,
    delegator_pays_xfer_fee: true, 
    founders_map: {}, 
    min_delegation_amt: 1.0, 
    owners_map: {tz1QgArbnGonQgZXqY3bLFwC93BUCicodfPX: 50}, 
    payment_address: cart2, 
    reactivate_zeroed: true,
    rules_map: {
       mindelegation: TOB, 
       KT1Dw98tugDFY2gTY1HpcMED4DEc5QKQJdvx: TOB,
       KT1Kqw7pHafDZNmfZsJFuwTnDyQknyzh4EPD: TOB
    },
    service_fee: 40.0, 
    specials_map: {}, 
    supporters_set: !!set {}
}
```

Error:
```
2020-11-02 08:06:23,554 - MainThread - Tezos Reward Distributor is Starting
2020-11-02 08:06:23,554 - MainThread - TRD version 5.13 is running in interactive mode.
2020-11-02 08:06:23,555 - MainThread - Arguments Configuration = {
 "initial_cycle": 400,
 "run_mode": 1,
 "release_override": 0,
 "payment_offset": 0,
 "network": "ALPHANET",
 "node_addr": "https://carthagenet.smartpy.io:443",
 "reward_data_provider": "rpc",
 "node_addr_public": "",
 "reports_base": "~/pymnt/reports",
 "config_dir": "~/pymnt/cfg",
 "dry_run": false,
 "dry_run_no_consumers": false,
 "executable_dirs": "~/,~/tezos",
 "docker": false,
 "background_service": false,
 "do_not_publish_stats": false,
 "verbose": false,
 "api_base_url": null,
 "retry_injected": false
}
2020-11-02 08:06:23,555 - MainThread - Anonymous statistics will be collected. See docs/statistics.rst for more information.
2020-11-02 08:06:24,542 - MainThread - Loading baking configuration file /home/ubuntu/pymnt/cfg/tz1QgArbnGonQgZXqY3bLFwC93BUCicodfPX.yaml
2020-11-02 08:06:25,499 - MainThread - Baking Configuration {
 "master_dict": {},
 "cfg_dict": {
  "baking_address": "tz1QgArbnGonQgZXqY3bLFwC93BUCicodfPX",
  "delegator_pays_ra_fee": true,
  "delegator_pays_xfer_fee": true,
  "founders_map": {},
  "min_delegation_amt": 1.0,
  "owners_map": {
   "tz1QgArbnGonQgZXqY3bLFwC93BUCicodfPX": 50
  },
  "payment_address": "cart2",
  "reactivate_zeroed": true,
  "rules_map": {
   "mindelegation": "TOB"
  },
  "service_fee": 40.0,
  "specials_map": {},
  "supporters_set": [],
  "__payment_address_type": null,
  "__payment_address_pkh": "tz1TTgLAf8915kj9ZuTyMboJtwdgtSEyKAEN",
  "__payment_address_manager": "tz1TTgLAf8915kj9ZuTyMboJtwdgtSEyKAEN",
  "__full_supporters_set": [
   "tz1QgArbnGonQgZXqY3bLFwC93BUCicodfPX"
  ],
  "__excluded_delegators_set_toe": [],
  "__excluded_delegators_set_tof": [],
  "__excluded_delegators_set_tob": [
   "mindelegation"
  ],
  "__destination_map": {}
 }
}
2020-11-02 08:06:25,499 - MainThread - --------------------------------------------
2020-11-02 08:06:25,499 - MainThread - BAKING ADDRESS is tz1QgArbnGonQgZXqY3bLFwC93BUCicodfPX
2020-11-02 08:06:25,499 - MainThread - PAYMENT ADDRESS is cart2
2020-11-02 08:06:25,499 - MainThread - --------------------------------------------
2020-11-02 08:06:25,500 - MainThread - Producer "producer" started
2020-11-02 08:06:25,501 - MainThread - If you want to send emails, populate email.ini file under current working directory.
2020-11-02 08:06:25,501 - MainThread - Consumer "consumer0" created
2020-11-02 08:06:25,502 - producer  - No failed payment files found under directory '/home/ubuntu/pymnt/reports/tz1QgArbnGonQgZXqY3bLFwC93BUCicodfPX/payments/failed'
2020-11-02 08:06:25,502 - producer_retry_fail - Retry Fail thread "producer_retry_fail" started
2020-11-02 08:06:26,503 - MainThread - Application start completed
2020-11-02 08:06:26,504 - MainThread - --------------------------------------------
2020-11-02 08:06:30,938 - producer  - Checking for pending payments : checking 400 <= 411 - (3 + 1) - 0
2020-11-02 08:06:30,939 - producer  - Payment cycle is 400
2020-11-02 08:06:31,644 - producer  - Unexpected error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ubuntu/pd/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 151, in __get_delegators_and_delgators_balances
    response = self.do_rpc_request(get_delegates_request)
  File "/home/ubuntu/pd/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 113, in do_rpc_request
    response = resp.json()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-11-02 08:06:31,871 - producer  - Total rewards before processing is 410,123,722 mutez.
2020-11-02 08:06:31,872 - producer  - Error at payment producer loop: 'division by zero', will try again.
Traceback (most recent call last):
  File "/home/ubuntu/pd/tezos-reward-distributor/src/pay/payment_producer.py", line 258, in try_to_pay
    reward_logs, total_amount = self.payment_calc.calculate(reward_model)
  File "/home/ubuntu/pd/tezos-reward-distributor/src/calc/phased_payment_calculator.py", line 57, in calculate
    rwrd_logs, total_rwrd_amnt = phase1.calculate(rwrd_logs, total_rwrd_amnt)
  File "/home/ubuntu/pd/tezos-reward-distributor/src/calc/calculate_phase1.py", line 62, in calculate
    new_total_amnt_multiplier = new_total_balance / total_balance
ZeroDivisionError: division by zero`
```
Attaching [Log Files here](https://www.codepile.net/pile/dbvM5PZP).

**Comment by kapiltez** [comment] 2020-11-03 17:09
Replacing the earlier command with updated command resolved this particular issue.

Old command: ` python3 src/main.py -M 1 -N ALPHANET -P rpc -A https://carthagenet.smartpy.io:443 -C 400 -V`
New command: ` python3 src/main.py -M 3 -N ALPHANET -P tzkt -A https://carthagenet.smartpy.io:443 -C 404 -V
`

**Comment by jdsika** [comment] 2020-11-05 07:16
This is definitly an unexpected behavior and will be fixed in the next release. Thank you for reporting it!

**Comment by utdrmac** [comment] 2020-11-12 17:39
@kapiltez The issue is with smartpy.io. Looking at your debug log file, TRD tried requesting this URL to fetch a list of your delegators:
`https://carthagenet.smartpy.io:443/chains/main/blocks/809216/context/delegates/tz1QgArbnGonQgZXqY3bLFwC93BUCicodfPX`

This returned back a bunch of HTML/JS content which is not what RPC's are supposed to return.

If I attempt that same RPC path on giganode, I get the correct response:

`https://testnet-tezos.giganode.io/chains/main/blocks/809216/context/delegates/tz1QgArbnGonQgZXqY3bLFwC93BUCicodfPX`

So, the -A path you are using is not a path to an RPC server that returns correct data. Please fix your parameters.

@jdsika I'll see about cleaning up the error message so it's more helpful

**Comment by jdsika** [comment] 2020-11-16 11:15
Did you already cleanup the error messages @utdrmac ?

**Closed** 2020-11-16 18:00 UTC
Labels: bug, critical
