### ISSUE TITLE
Delegates haven't received a payout

### ISSUE THREAD

**Issue by akrykunenko** [tezos-reward-distributor-organization/tezos-reward-distributor#321] opened 2020-11-21 14:53 UTC
**Describe the bug**
After updating to v8.0, I experienced the following issue:
- almost all delegates received rewards as expected
- some addresses haven't received rewards --> they were redirected to the baker's account

Affected delegates are completely missing in the _pymnt/reports/**redacted**/calculations/293.csv_ file. Which means that there is nothing to do with either config or zero balance. I double-checked that they were delegated to me during this cycle.

**To Reproduce**
1. Upgrade to v8.0
2. Launch payments with the command specified below
3. Get a timeout from prpc (the only unusual thing I spotted)
4. TRD run finished successfully, but some delegates missing their reward 

**Expected behavior**

**Screenshots**
Note that processing started just after timeout from giganode:
![image](https://user-images.githubusercontent.com/48133983/99880078-d0928580-2c19-11eb-81fe-b7118362a77d.png)

**Environment**
 - Source Code Build or Docker: **Source Code Build**
 - Chain mainnet, zeronet, alphanet: **Mainnet**
 - actual command used: **python3 src/main.py -C 293 -M 3**
 - Operating system / system specification: **Ubuntu 18.04 LTS**

**Comment by dansan566** [comment] 2020-11-21 14:56
@utdrmac @amzid Is there a quick way to figure out who also didn't receive a reward out of 1300 delegates?

**Comment by BakeTz** [comment] 2020-11-21 21:29
I have the same problem. The payment system sent 36 payments instead of 437.

**Comment by jdsika** [comment] 2020-11-21 21:39
@amzid highest prio!

**Comment by utdrmac** [comment] 2020-11-21 22:07
@BakeTz Need to see your log file. Please find one of us on slack if you don't want to upload it to this issue.

**Comment by utdrmac** [comment] 2020-11-21 22:14
In looking at @akrykunenko 's log file, I see this:

```
2020-11-21 12:50:38,661 - producer  - Delegator info (1150/1890) fetched: address KT1C1LTP1KaPUPahBaFAGQYyS6BMpsjmMBuR, staked balance 101243, current balance 101243 
2020-11-21 12:50:44,774 - producer  - Unexpected error: HTTPSConnectionPool(host='mainnet-tezos.giganode.io', port=443): Read timed out. (read timeout=5)
Traceback (most recent call last):
```

So, it appears that the timeout threw an exception which completely stopped the fetching of the remaining delegator's balances. This obviously should not have happened. Instead, the exception should have either A) stopped the entire cycle's payouts, slept and tried again, or B) slept and reattempted to fetch #1150 and continue with the remaining delegates.

**Comment by utdrmac** [comment] 2020-11-21 23:38
@jdsika This is actually fixed in #316 
In that PR, there's an explicit catch of timeout exceptions which cause a sleep/wait/retry effect.

**Comment by utdrmac** [comment] 2020-11-22 01:36
I just added even more exception handling logic to #316

**Comment by BakeTz** [comment] 2020-11-22 04:53
@utdrmac Please see my log below:
RUN: python3 src/main.py

LOG:
2020-11-20 21:32:41,536 - producer_retry_fail - No failed payment files found under directory '/home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/payments/failed'
2020-11-20 22:22:33,374 - producer  - Checking for pending payments : checking 293 <= 298 - (5 + 1) - 0
2020-11-20 22:22:33,374 - producer  - No pending payments for cycle 293, current cycle is 298
2020-11-20 22:32:41,537 - producer_retry_fail - No failed payment files found under directory '/home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/payments/failed'
2020-11-20 23:32:41,538 - producer_retry_fail - No failed payment files found under directory '/home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/payments/failed'
2020-11-20 23:41:51,894 - producer  - Checking for pending payments : checking 293 <= 298 - (5 + 1) - 0
2020-11-20 23:41:51,894 - producer  - No pending payments for cycle 293, current cycle is 298
2020-11-20 23:44:07,048 - producer  - Checking for pending payments : checking 293 <= 298 - (5 + 1) - 0
2020-11-20 23:44:07,048 - producer  - No pending payments for cycle 293, current cycle is 298
2020-11-20 23:45:22,192 - producer  - Checking for pending payments : checking 293 <= 299 - (5 + 1) - 0
2020-11-20 23:45:22,192 - producer  - Current level within the cycle is -1; Requested offset is 0; Waiting for 1 more blocks.
2020-11-20 23:46:27,341 - producer  - Checking for pending payments : checking 293 <= 299 - (5 + 1) - 0
2020-11-20 23:46:27,341 - producer  - Payment cycle is 293
### https://mainnet-tezos.giganode.io/chains/main/blocks/head
2020-11-20 23:49:02,111 - producer  - Unexpected error: HTTPSConnectionPool(host='mainnet-tezos.giganode.io', port=443): Read timed out. (read timeout=5)
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 259, in __get_delegators_and_delgators_balances
	d_info["current_balance"] = self.__get_current_balance_of_delegator(delegator)
  File "/home/tzpc-2/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 298, in __get_current_balance_of_delegator
	raise e from e
  File "/home/tzpc-2/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 291, in __get_current_balance_of_delegator
	current_balance_response = self.do_rpc_request(get_current_balance_request, time_out=5)
  File "/home/tzpc-2/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 114, in do_rpc_request
	resp = requests.get(request, timeout=time_out)
  File "/home/tzpc-2/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
	return request('get', url, params=params, **kwargs)
  File "/home/tzpc-2/.local/lib/python3.8/site-packages/requests/api.py", line 60, in request
	return session.request(method=method, url=url, **kwargs)
  File "/home/tzpc-2/.local/lib/python3.8/site-packages/requests/sessions.py", line 524, in request
	resp = self.send(prep, **send_kwargs)
  File "/home/tzpc-2/.local/lib/python3.8/site-packages/requests/sessions.py", line 637, in send
	r = adapter.send(request, **kwargs)
  File "/home/tzpc-2/.local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
	raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='mainnet-tezos.giganode.io', port=443): Read timed out. (read timeout=5)
2020-11-20 23:49:04,029 - producer  - Total rewards before processing is 1,670,571,457 mutez.
2020-11-20 23:49:04,034 - producer  - Total rewards after processing is 1,670,571,457 mutez.
2020-11-20 23:49:04,034 - producer  - Total amount to pay is 1,670,571,457 mutez
2020-11-20 23:49:04,034 - producer  - Difference between total rewards and total payment amount is 0 mutez. This is due to floating point arithmetic. (max allowed diff is 10)
2020-11-20 23:49:05,036 - consumer0 - Starting payments for cycle 293
2020-11-20 23:49:05,040 - consumer0 - Transfer fee is 0.000574 XTZ and is paid by Delegator
2020-11-20 23:49:05,040 - consumer0 - Reactivation fee is 0.257000 XTZ and is paid by Delegator
2020-11-20 23:49:05,041 - consumer0 - Payment amount cutoff is 0.000575 XTZ
2020-11-20 23:49:05,041 - consumer0 - 56 payment items to process
2020-11-20 23:49:05,444 - consumer0 - Total amount to pay out is 1,670,698,465 mutez.
2020-11-20 23:49:05,445 - consumer0 - Current balance in payout address is 2,500,067,736 mutez.
2020-11-20 23:49:05,445 - consumer0 - 36 payments will be done in 1 batches
2020-11-20 23:49:05,445 - consumer0 - The payout address will soon run out of funds. The current balance, 2,500,067,736 mutez, might not be sufficient for the next cycle
2020-11-20 23:49:06,165 - consumer0 - [TelegramPlugin] Notification 'Low Payment Address Funds Warning' sent
2020-11-20 23:49:07,771 - consumer0 - Operation hash is ooa7gyp3VYr8jVY96Gn2SSkRjfSp3QA14U8ank6ooCsYghpU8NT
2020-11-20 23:49:07,772 - consumer0 - Waiting for operation ooa7gyp3VYr8jVY96Gn2SSkRjfSp3QA14U8ank6ooCsYghpU8NT to be included. Please be patient until the block has 1 confirmation(s)
2020-11-20 23:49:09,055 - producer  - Calculation report is created at '/home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/calculations/293.csv'
2020-11-20 23:49:09,055 - producer  - Reward creation is done for cycle 293, created 58 rewards.
2020-11-20 23:49:24,164 - producer  - Checking for pending payments : checking 294 <= 299 - (5 + 1) - 0
2020-11-20 23:49:24,164 - producer  - No pending payments for cycle 294, current cycle is 299
2020-11-20 23:51:29,711 - consumer0 - Operation ooa7gyp3VYr8jVY96Gn2SSkRjfSp3QA14U8ank6ooCsYghpU8NT is included
2020-11-20 23:51:29,713 - consumer0 - Payment of batch 1 is complete, in 1 attempt(s)
2020-11-20 23:51:29,713 - consumer0 - Processing completed for 36 payment items.
2020-11-20 23:51:29,714 - consumer0 - Payment report is created at '/home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/payments/done/293.csv'
2020-11-20 23:51:29,720 - producer_retry_fail - No failed payment files found under directory '/home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/payments/failed'
2020-11-20 23:51:30,405 - consumer0 - [TelegramPlugin] Notification 'Reward Payouts for Cycle 293 Completed Successfully!' sent
2020-11-20 23:51:30,417 - consumer0 - Sending anonymous statistics; See docs/statistics.rst for more information.

**Comment by utdrmac** [comment] 2020-11-22 05:03
@BakeTz Yes, the analysis of your logs looks extremely similar to @akrykunenko, thus the issue is the same. When the remote RPC call timed out, TRD simply returned to the calling function rather than raise an exception which should have aborted the entire payout run and forced a sleep/try-again loop.
This should be corrected in the mentioned PR #316

**Comment by jdsika** [comment] 2020-11-22 12:54
@amzid please confirm that this has been resolved and close the issue

**Comment by amzid** [comment] 2020-11-22 16:02
I did not get any timeouts with the tests I did, but it would be great if @BakeTz and @dansan566 can confirm this as well from their side and using their local nodes.

**Comment by BakeTz** [comment] 2020-11-22 19:58
@amzid can you please give me some instructions on how can I test it properly?

**Comment by jdsika** [comment] 2020-11-23 07:32
> 
> 
> I did not get any timeouts with the tests I did, but it would be great if @BakeTz and @dansan566 can confirm this as well from their side and using their local nodes.

The question is: Are timeouts now correctly handled and retired until they are successfull? It is not useful to skip certain addresses and continue with the next as if nothing happend. At least the addresses need to be flagged in the payout csv for a retry and need to be automatically retired in a few cycles

**Comment by amzid** [comment] 2020-11-23 15:19
> @amzid can you please give me some instructions on how can I test it properly?

Please pull the current master and check -with dry run for example- if you get all expected payment items. You can run the same command above adding the -D flag and then check the new reports under the TRD directory (calculations and payments).

**Comment by utdrmac** [comment] 2020-11-23 17:16
@jdsika Yes, timeouts at the requests.get(URL) are caught and retried immediately in some situations (like fetching delegator balances). In others, the entire payout process is aborted and attempted again after a sleep period.

**Comment by BakeTz** [comment] 2020-11-24 17:50
@amzid Look like everything works fine to me. Thank you!

**Closed** 2020-11-24 17:52 UTC
Labels: bug, critical
