### ISSUE TITLE
Move some command line parameters to the config file

### ISSUE THREAD

**Issue by ericlavoie** [tezos-reward-distributor-organization/tezos-reward-distributor#539] opened 2022-01-04 20:50 UTC
**Is your feature request related to a problem? Please describe.**

Some command line parameters, would make more sense to be in the configuration file.
The issue is to be sure any of these parameters are not needed before the configuration is loaded and run.
It would make it easier to modify some parameters (no need to restart a service)

**Describe the solution you'd like**
Here are some I fgure should be specific to a config:
--release_override
--payment_offset
--reward_data_provider
--initial_cycle

**Comment by nicolasochem** [comment] 2022-01-13 23:04
yes! Duplicate of https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/issues/424

**Closed** 2022-03-23 01:45 UTC
Labels: enhancement
