### ISSUE TITLE
specials_map not resulting in a payout

### ISSUE THREAD

**Issue by sriney-staked** [tezos-reward-distributor-organization/tezos-reward-distributor#290] opened 2020-10-29 17:53 UTC
**Describe the bug**
Before upgrading to commit: 5f64db8e47270648117171210ca04e0d7ab0df18, a single address in the "special_map" list was configured with a non-standard rate, and the payment was generated.  The current version is not.

**To Reproduce**
1. add an address to the specials_map
2. do a dry run `python3 src/main.py -E /usr/local/bin -M 3 -C 285 -P tzstats -D`
3. note that the address is not set to be paid out.

**Expected behavior**
A payout txn for the address in the specials_map

**Environment**
 - commit 5f64db8e47270648117171210ca04e0d7ab0df18

**Comment by amzid** [comment] 2020-10-31 13:43
Thank you for reporting the bug. Unfortunately, I am not able to reproduce the behavior. Can you provide more information about the bug/log file? Is the address (of the specials_map) included in the calculations report?

**Comment by utdrmac** [comment] 2020-11-12 17:49
@sriney-staked Any updates here?

**Comment by utdrmac** [comment] 2020-11-26 15:30
@sriney-staked Unless we can get some more info from you, we cannot reproduce this issue and will close this report for now. Please re-open if you can get us the logs. Thanks

**Closed by utdrmac** 2020-11-26 15:30 UTC
Labels: blocked, bug
